# Generated by Django 3.0.3 on 2020-02-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0002_auto_20200212_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='formdata',
        ),
        migrations.AddField(
            model_name='formdata',
            name='formData',
            field=models.TextField(default='m'),
        ),
    ]
