# Generated by Django 3.0.3 on 2020-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0005_formfiller'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('filledData', models.TextField()),
            ],
        ),
    ]
