# Generated by Django 3.0.3 on 2020-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0007_formdata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='owner',
            field=models.CharField(default='pseudodev', max_length=120),
        ),
    ]
