# Generated by Django 3.0.3 on 2020-03-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0009_auto_20200301_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('formData', models.CharField(default='m', max_length=10000)),
                ('owner', models.CharField(max_length=120)),
            ],
        ),
    ]
